runtime: nodejs18
env: standard
instance_class: F1

handlers:
  - url: /images
    static_dir: public/images
  - url: /javascripts
    static_dir: public
  - url: /stylesheets
    static_dir: public

  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto
